[package]
name = "OpenShelf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.15.0"
id3 = "1.0.2"
rustbreak = "2.0.0"
