[package]
name = "PodmanTest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.15.0"
lofty = "0.5.3"
serde = "1.0.136"
lazy_static = "1.4.0"
reqwest = "0.11.10"
termion = "1.5.6"

